import React from 'react'

/**
 * using useMemo hook
 */

export const UseMemo = () => {

    // an expensive function
    const autoGeneratedIds = React.useMemo<string[] >(()=>{
        // generate 100 random string uuid's
        return Array.from({ length: 100 }, () =>
            Math.random().toString(36).substr(2, 9)
          );
    },[]);

  return (
    <div>
      
    </div>
  )
}
